config/routes.rb
Rails.application.routes.draw do
  root 'misc#index'

  devise_for :librarians, controllers: { sessions: 'librarian/sessions', registrations: 'librarian/registrations' }
  devise_for :admins, controllers: { sessions: 'admin/sessions', registrations: 'admin/registrations' }
  devise_for :students, controllers: { omniauth_callbacks: 'student/omniauth_callbacks', sessions: 'student/sessions', registrations: 'student/registrations' }

  resources :borrowing_histories
  resources :book_hold_requests
  resources :students
  resources :libraries
  resources :books
  resources :librarians 

  get 'home/' => 'application#home'
  get 'admin_dashboard/' => 'misc#admin_dashboard', :as => :admin_dashboard
  get 'approve_librarian/:id' => 'librarians#approve_librarian', :as => :approve_librarian
  get 'librarian_dashboard/' => 'misc#librarian_dashboard', :as => :librarian_dashboard
  
  post 'checkout/:id' => 'books#checkout_book', :as => :checkout
  post 'request/:id' => 'books#request_book', :as => :request
  post 'return/:id' => 'books#return_book', :as => :return
  get 'bookmarks/:id' => 'books#bookmark_toggle', :as => :bookmark
  get 'bookmarks/' => 'books#view_bookmarks', :as => :view_bookmark
  get 'student_checkouts/' => 'books#view_student_checkouts', :as => :view_student_checkouts
  
  get 'student_hold_requests/' => 'book_hold_requests#student_hold_requests', :as => :student_hold_requests
  get 'book_hold_request_approve/:id' => 'book_hold_requests#approve', :as => :approve_book_hold_request

  get 'fine_details/' => 'student#fine_details', :as => :fine_details
  get 'librarian_approval/' => 'misc#librarian_approval', :as => :librarian_approval
  
  get 'library_checkouts/' => 'borrowing_histories#view_library_checkouts', :as => :view_library_checkouts
  get 'library_borrowing_histories/' => 'borrowing_histories#view_library_borrowing_history', :as => :view_library_borrowing_history

  get 'libraries_overdue/:id' => 'libraries#overdue_books', :as => :libraries_overdue

  get 'list_students/' => 'students#list', :as => :list_students

end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]
  belongs_to :university
  enum educational_level: [:undergraduate, :graduate, :phd]
  
  has_many :student_bookmarks, dependent: :destroy    
  has_many :borrowing_histories, dependent: :destroy    
  has_many :book_hold_requests, dependent: :destroy    

  def self.new_with_session(params, session)
    super.tap do |student|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        student.email = data["email"] if student.email.blank?
      end
    end
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |student|
    student.email = auth.info.email
    student.password = Devise.friendly_token[0, 20]
    student.name = auth.info.name   # assuming the student model has a name
    student.university_id = 1
    #student.degree_to_book_mappings_id = 1
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # student.skip_confirmation!
  end
end

  has_many :book_hold_requests, dependent: :destroy   
   
  def self.calculate_overdue_fine(student_id) 
    overdue_fine = 0 
    checkout_books = BorrowingHistory.fetch_all_active_books_by_student(student_id)

    checkout_books.map { |checkout_book|
      library_id = BookLibraryMapping.fetch_library_for_book(checkout_book.book_id)

      if not library_id.nil?
        library = Library.find(library_id)
        max_days_blocking = library.max_days_blocking 
        overdue_fine += ((Date.today - checkout_book.issue_date).abs + 1) * library.overdue_fines
      end
    }

    overdue_fine
  end
  
end

app/controllers/student/omniauth_callbacks_controller.rb
class Student::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
    def facebook
      @student = Student.from_omniauth(request.env["omniauth.auth"])
      if request.env["omniauth.auth"].info.email.blank?
        redirect_to "/students/auth/facebook?auth_type=rerequest&scope=email"
        return
      end
      if @student.persisted?
        sign_in_and_redirect @student, event: :authentication
        set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_student_registration_url
      end
    end
    def failure
      redirect_to root_path
    end
   end

app/controllers/student/registrations_controller.rb
# frozen_string_literal: true

class Student::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  before_action :get_all_universities

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  #def create
  #  super
  #end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :password, :university_id, :educational_level])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :university_id, :educational_level])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end

  def get_all_universities
    @universities = University.all()
  end
end

app/controllers/student/sessions_controller.rb
# frozen_string_literal: true

class Student::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
    super(resource)
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_student! unless :admin_signed_in?
  
  # GET /students
  # GET /students.json
  def index
  end

  def list
    @students = Student.all
    render "_list"
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fine_details
    @active_books = BorrowingHistory.fetch_all_active_books_by_student(current_student.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:email, :name, :password, :educational_level, :university_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :educational_level %>
    <%= select("student", "educational_level", [["Undergraduate", "undergraduate"], ["Graduate", "graduate"],["PhD", "phd"]]) %>

  </div>

  <div class="field">
    <%= form.label :university %>
    <%= select("student", "university_id", University.all.collect{ |l| [ l.name, l.id] }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_list.html.erb
<p id="notice"><%= notice %></p>

<h3>Students</h3>

<table class=" w3-table-all">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Password</th>
      <th>Educational level</th>
      <th>University</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.email %></td>
        <td><%= student.name %></td>
        <td><%= student.password %></td>
        <td><%= student.educational_level %></td>
        <td><%= student.university_id %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/edit.html.erb
<p id="notice"><%= notice %></p>

<h3>Editing Student</h3>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |

app/views/students/fine_details.html.erb
<h3>Books Incurring fines:</h3>

<div>

<table class="w3-table">
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Title</th>
      <th>Issued Date</th>
      <th>Summary</th>
      <th>Special</th>
      <th>Library</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @active_books.each do |active_book| %>
        <% book = Book.find(active_book.book_id) %>
        <% library = Library.find(BookLibraryMapping.fetch_library_for_book(active_book.book_id)) %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= book.title %></td>
        <td><%= active_book.issue_date %></td>
        <td><%= book.summary %></td>
        <td><%= book.special %></td>
        <td><%= library.name %></td>
        <td><%= library.location %></td>
        <td><%= link_to 'Details', book %></td>
        <% if current_admin or current_librarian%>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <% end %>

        <% if student_signed_in? %>

        <% if StudentBookmark.where(:book_id => book.id, :student_id => current_student.id).length == 0 %>
        <td><%= link_to 'Bookmark', bookmark_path(book) %></td>
        <% else %>
        <td><%= link_to 'Unbookmark', bookmark_path(book) %></td>
        <% end %>

        <% if BorrowingHistory.is_book_active?(current_student.id, book.id)%>
        <td><%= button_to 'Return', return_path(book) %></td>
        <% else %>
        <% if BookLibraryMapping.fetch_book_quantity(book.id) != 0 and !book.special%>
        <td><%= button_to 'Checkout', checkout_path(book) %></td>
        <% else %>
        <% if BookHoldRequest.is_requested?(current_student.id, book.id)%>
        <td><%= button_to 'Cancel Request', request_path(book) %></td>
        <% else %>
        <td><%= button_to 'Request', request_path(book) %></td>
        <% end %>
        <% end %>
        <% end %>
        <% end %>
        
        <% if current_admin%>        
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div >
<% if current_admin%>
<%= button_to 'New Book', new_book_path %>
<% end%>
</div>

app/views/students/list.html.erb
<p id="notice"><%= notice %></p>

<h3>Students</h3>

<table class=" w3-table-all">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Password</th>
      <th>Educational level</th>
      <th>University</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.email %></td>
        <td><%= student.name %></td>
        <td><%= student.password %></td>
        <td><%= student.educational_level %></td>
        <td><%= student.university_id %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<p id="notice"><%= notice %></p>

<h3>New Student</h3>

<%= render 'form', student: @student %>

app/views/students/search.html.erb
<input type="text" placeholder="Search..">

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @student.password %>
</p>

<p>
  <strong>Educational level:</strong>
  <%= @student.educational_level %>
</p>

<p>
  <strong>University:</strong>
  <%= @student.university_id %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |