config/routes.rb
Rails.application.routes.draw do
  root 'misc#index'

  devise_for :librarians, controllers: { sessions: 'librarian/sessions', registrations: 'librarian/registrations' }
  devise_for :admins, controllers: { sessions: 'admin/sessions', registrations: 'admin/registrations' }
  devise_for :students, controllers: { omniauth_callbacks: 'student/omniauth_callbacks', sessions: 'student/sessions', registrations: 'student/registrations' }

  resources :borrowing_histories
  resources :book_hold_requests
  resources :students
  resources :libraries
  resources :books
  resources :librarians 

  get 'home/' => 'application#home'
  get 'admin_dashboard/' => 'misc#admin_dashboard', :as => :admin_dashboard
  get 'approve_librarian/:id' => 'librarians#approve_librarian', :as => :approve_librarian
  get 'librarian_dashboard/' => 'misc#librarian_dashboard', :as => :librarian_dashboard
  
  post 'checkout/:id' => 'books#checkout_book', :as => :checkout
  post 'request/:id' => 'books#request_book', :as => :request
  post 'return/:id' => 'books#return_book', :as => :return
  get 'bookmarks/:id' => 'books#bookmark_toggle', :as => :bookmark
  get 'bookmarks/' => 'books#view_bookmarks', :as => :view_bookmark
  get 'student_checkouts/' => 'books#view_student_checkouts', :as => :view_student_checkouts
  
  get 'student_hold_requests/' => 'book_hold_requests#student_hold_requests', :as => :student_hold_requests
  get 'book_hold_request_approve/:id' => 'book_hold_requests#approve', :as => :approve_book_hold_request

  get 'fine_details/' => 'student#fine_details', :as => :fine_details
  get 'librarian_approval/' => 'misc#librarian_approval', :as => :librarian_approval
  
  get 'library_checkouts/' => 'borrowing_histories#view_library_checkouts', :as => :view_library_checkouts
  get 'library_borrowing_histories/' => 'borrowing_histories#view_library_borrowing_history', :as => :view_library_borrowing_history

  get 'libraries_overdue/:id' => 'libraries#overdue_books', :as => :libraries_overdue

  get 'list_students/' => 'students#list', :as => :list_students

end

app/models/library.rb
class Library < ApplicationRecord
    belongs_to :university
    has_many :book_library_mappings, dependent: :destroy    
    has_many :book_hold_requests, dependent: :destroy    
    has_many :librarians, dependent: :destroy    

    validates :name, presence: true
    validates :max_days_blocking, presence: true
    validates :overdue_fines, presence: true    
    
    def self.get_overdue_books(library_id)
        overdue_books = Array.new
        checkout_books = BorrowingHistory.all.select { |bh|
            library_id == BookLibraryMapping.fetch_library_for_book(bh.book_id)
        }

        checkout_books.map { |checkout_book|
            if(checkout_book.issue_date < Date.today)
                overdue_books.push(checkout_book)
            end
        }
        overdue_books
    end

    def self.fetch_libraries_by_university(university_id)
        Library.all.select {|l| l.university_id == university_id}
    end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]
  before_action :test_user, only: [:edit, :update, :destroy]

  def test_user
		if not (admin_signed_in? or  librarian_signed_in?)
			redirect_to('/')
    end
  end

  # GET /libraries
  # GET /libraries.json
  def index
    if current_admin
      @libraries = Library.all
    elsif current_librarian
      library_id = current_librarian.library_id
      @libraries = Array.new.push(Library.find(library_id))
    elsif current_student
      @libraries = Library.fetch_libraries_by_university(current_student.university_id)
    end
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def overdue_books
    @library = Library.find(current_librarian.library_id)
    @overdue_books = Library.get_overdue_books(@library.id)
    @overdue_books
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:name, :location, :max_days_blocking, :overdue_fines, :university_id)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with(model: library, local: true) do |form| %>
  <% if library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
        <% library.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>

  <div class="field">
    <%= form.label :max_days_blocking %>
    <%= form.number_field :max_days_blocking %>
  </div>

  <div class="field">
    <%= form.label :overdue_fines %>
    <%= form.number_field :overdue_fines %>
  </div>

  <div class="field">
    <%= form.label :university_id %>
    <%= select("library", "university_id", University.all.collect{ |u| [ u.name, u.id] }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h3>Editing Library</h3>

<%= render 'form', library: @library %>

<%= link_to 'Show', @library %> |

app/views/libraries/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Libraries</h3>
<table class="w3-table-all">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Max days blocking</th>
      <th>Overdue fines</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.name %></td>
        <td><%= library.location %></td>
        <td><%= library.max_days_blocking %></td>
        <td><%= library.overdue_fines %></td>
        <td><%= link_to 'Show', library %></td>
        <% if current_admin or current_librarian %>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <% end %>
        <% if current_admin %>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_admin %>
<%= button_to 'New Library', new_library_path, method: :get %>
<% end %>

app/views/libraries/new.html.erb
<h3>New Library</h3>

<%= render 'form', library: @library %>

app/views/libraries/overdue_books.html.erb
<% if @overdue_books.length == 0 or @overdue_books.nil? %>
    <br><p> No books overdue :) </p>
  <% else %>
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Title</th>
      <th>Language</th>
      <th>Published</th>
      <th>Edition</th>
      <th class="hidden">Image</th>
      <th>Subject</th>
      <th>Summary</th>
      <th>Special</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @overdue_books.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= book.title %></td>
        <td><%= book.language %></td>
        <td><%= book.published %></td>
        <td><%= book.edition %></td>
        <td class="hidden"><%= book.image %></td>
        <td><%= book.subject %></td>
        <td><%= book.summary %></td>
        <td><%= book.special %></td>
        <td><%= link_to 'Details', book %></td>
        <% if current_admin or current_librarian%>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <% end %>

        <% if student_signed_in? %>

        <% if StudentBookmark.where(:book_id => book.id, :student_id => current_student.id).length == 0 %>
        <td><%= link_to 'Bookmark', bookmark_path(book) %></td>
        <% else %>
        <td><%= link_to 'Unbookmark', bookmark_path(book) %></td>
        <% end %>

        <% if BorrowingHistory.is_book_active?(current_student.id, book.id)%>
        <td><%= button_to 'Return', return_path(book) %></td>
        <% else %>
        <% if BookLibraryMapping.fetch_book_quantity(book.id) != 0 and !book.special%>
        <td><%= button_to 'Checkout', checkout_path(book) %></td>
        <% else %>
        <% if BookHoldRequest.is_requested?(current_student.id, book.id)%>
        <td><%= button_to 'Cancel Request', request_path(book) %></td>
        <% else %>
        <td><%= button_to 'Request', request_path(book) %></td>
        <% end %>
        <% end %>
        <% end %>
        <% end %>
        
        <% if current_admin or current_librarian %>        
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
  <% end %>

app/views/libraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @library.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @library.location %>
</p>

<p>
  <strong>Max days blocking:</strong>
  <%= @library.max_days_blocking %>
</p>

<p>
  <strong>Overdue fines:</strong>
  <%= @library.overdue_fines %>
</p>

<% if current_admin %>
<%= link_to 'Edit', edit_library_path(@library) %> 
<%end%>

<br><br><br>
<h3>Books in <%= @library.name %></h3>
<hr>
<%= render "books/search"%>
<%= render "books/list", :@books => Book.fetch_books_by_ids(BookLibraryMapping.fetch_book_by_library(@library.id))%>