config/routes.rb
Rails.application.routes.draw do
  root 'misc#index'

  devise_for :librarians, controllers: { sessions: 'librarian/sessions', registrations: 'librarian/registrations' }
  devise_for :admins, controllers: { sessions: 'admin/sessions', registrations: 'admin/registrations' }
  devise_for :students, controllers: { omniauth_callbacks: 'student/omniauth_callbacks', sessions: 'student/sessions', registrations: 'student/registrations' }

  resources :borrowing_histories
  resources :book_hold_requests
  resources :students
  resources :libraries
  resources :books
  resources :librarians 

  get 'home/' => 'application#home'
  get 'admin_dashboard/' => 'misc#admin_dashboard', :as => :admin_dashboard
  get 'approve_librarian/:id' => 'librarians#approve_librarian', :as => :approve_librarian
  get 'librarian_dashboard/' => 'misc#librarian_dashboard', :as => :librarian_dashboard
  
  post 'checkout/:id' => 'books#checkout_book', :as => :checkout
  post 'request/:id' => 'books#request_book', :as => :request
  post 'return/:id' => 'books#return_book', :as => :return
  get 'bookmarks/:id' => 'books#bookmark_toggle', :as => :bookmark
  get 'bookmarks/' => 'books#view_bookmarks', :as => :view_bookmark
  get 'student_checkouts/' => 'books#view_student_checkouts', :as => :view_student_checkouts
  
  get 'student_hold_requests/' => 'book_hold_requests#student_hold_requests', :as => :student_hold_requests
  get 'book_hold_request_approve/:id' => 'book_hold_requests#approve', :as => :approve_book_hold_request

  get 'fine_details/' => 'student#fine_details', :as => :fine_details
  get 'librarian_approval/' => 'misc#librarian_approval', :as => :librarian_approval
  
  get 'library_checkouts/' => 'borrowing_histories#view_library_checkouts', :as => :view_library_checkouts
  get 'library_borrowing_histories/' => 'borrowing_histories#view_library_borrowing_history', :as => :view_library_borrowing_history

  get 'libraries_overdue/:id' => 'libraries#overdue_books', :as => :libraries_overdue

  get 'list_students/' => 'students#list', :as => :list_students

end

app/models/book_hold_request.rb
class BookHoldRequest < ApplicationRecord
  belongs_to :student
  belongs_to :book
  belongs_to :library

  enum reason: [:special, :unavailable, :max_reached]
  validates :reason, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def self.is_requested?(student_id, book_id)
    if BookHoldRequest.where(:student_id => student_id, :book_id => book_id).length != 0
      true
    else
      false
    end
  end

  def self.fetch_hold_requests_by_student(student_id)
    where(:student_id => student_id)
  end


  def self.fetch_hold_requests_by_book(book_id)
    where(:book_id => book_id).order('created_at')
  end

end

app/controllers/book_hold_requests_controller.rb
class BookHoldRequestsController < ApplicationController
  before_action :set_book_hold_request, only: [:show, :edit, :update, :destroy, :approve]

  # GET /book_hold_requests
  # GET /book_hold_requests.json
  def index
    @book_hold_requests = BookHoldRequest.all
  end

  # GET /book_hold_requests/1
  # GET /book_hold_requests/1.json
  def show
  end

  # GET /book_hold_requests/new
  def new
    @book_hold_request = BookHoldRequest.new
  end

  # GET /book_hold_requests/1/edit
  def edit
  end

  def student_hold_requests
    if current_student
      @hold_requests =  BookHoldRequest.fetch_hold_requests_by_student(current_student.id)
    end
  end

  # POST /book_hold_requests
  # POST /book_hold_requests.json
  def create
    @book_hold_request = BookHoldRequest.new(book_hold_request_params)

    respond_to do |format|
      if @book_hold_request.save
        format.html { redirect_to @book_hold_request, notice: 'Book hold request was successfully created.' }
        format.json { render :show, status: :created, location: @book_hold_request }
      else
        format.html { render :new }
        format.json { render json: @book_hold_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_hold_requests/1
  # PATCH/PUT /book_hold_requests/1.json
  def update
    respond_to do |format|
      if @book_hold_request.update(book_hold_request_params)
        format.html { redirect_to @book_hold_request, notice: 'Book hold request was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_hold_request }
      else
        format.html { render :edit }
        format.json { render json: @book_hold_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_hold_requests/1
  # DELETE /book_hold_requests/1.json
  def destroy
    @book_hold_request.destroy
    respond_to do |format|
      format.html { redirect_to book_hold_requests_url, notice: 'Book hold request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve
    book_id = @book_hold_request.book_id
    @book_hold_request.destroy
    BooksController.new.checkout_book
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_hold_request
      @book_hold_request = BookHoldRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_hold_request_params
      params.require(:book_hold_request).permit(:student_id, :book_id, :library_id, :reason)
    end
end

app/helpers/book_hold_requests_helper.rb
module BookHoldRequestsHelper
end

app/views/book_hold_requests/_form.html.erb
<%= form_with(model: book_hold_request, local: true) do |form| %>
  <% if book_hold_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_hold_request.errors.count, "error") %> prohibited this book_hold_request from being saved:</h2>

      <ul>
        <% book_hold_request.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.text_field :book_id %>
  </div>

  <div class="field">
    <%= form.label :library_id %>
    <%= form.text_field :library_id %>
  </div>

  <div class="field">
    <%= form.label :reason %>
    <%= form.number_field :reason %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_hold_requests/_index.html.erb
<table class="w3-table-all">
  <thead>
    <tr>
      <th>Student</th>
      <th>Book</th>
      <th>Library</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_hold_requests.each do |book_hold_request| %>
      <tr>
        <td><%= book_hold_request.student_id %></td>
        <td><%= book_hold_request.book_id %></td>
        <td><%= book_hold_request.library_id %></td>
        <td><%= book_hold_request.reason %></td>
        <td><%= link_to 'Show', book_hold_request %></td>
        <td><%= link_to 'Approve', approve_book_hold_request_path(book_hold_request) %></td>
        <td><%= link_to 'Destroy', book_hold_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book Hold Request', new_book_hold_request_path %>

app/views/book_hold_requests/edit.html.erb
<h3>Editing Book Hold Request</h3>

<%= render 'form', book_hold_request: @book_hold_request %>

<%= link_to 'Show', @book_hold_request %> |

app/views/book_hold_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Book Hold Requests</h3>

<%= render "book_hold_requests/index", :@book_hold_requests => @book_hold_requests%>

app/views/book_hold_requests/new.html.erb
<h3>New Book Hold Request</h3>

<%= render 'form', book_hold_request: @book_hold_request %>

app/views/book_hold_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @book_hold_request.student_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @book_hold_request.book_id %>
</p>

<p>
  <strong>Library:</strong>
  <%= @book_hold_request.library_id %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @book_hold_request.reason %>
</p>

<%= link_to 'Edit', edit_book_hold_request_path(@book_hold_request) %> |

app/views/book_hold_requests/student_hold_requests.html.erb
<h3>Book Hold Requests</h3>

<%= render "books/search"%>


<div>
<% if @hold_requests.empty? or @hold_requests.nil? %>
    <br><p> No hold requests found :( </p>
  <% else %>
<table class="w3-table-all">
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Title</th>
      <th>Language</th>
      <th>Published</th>
      <th>Summary</th>
      <th>Special</th>
      <th>Library</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hold_requests.each do |hold_request| %>
        <% book = Book.find(hold_request.book_id) %>
        <% library = Library.find(hold_request.library_id) %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= book.title %></td>
        <td><%= book.language %></td>
        <td><%= book.published %></td>
        <td><%= book.summary %></td>
        <td><%= book.special %></td>
        <td><%= library.name %></td>
        <td><%= library.location %></td>
        <td><%= link_to 'Details', book %></td>
        <% if current_admin or current_librarian%>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <% end %>

        <% if student_signed_in? %>

        <% if StudentBookmark.where(:book_id => book.id, :student_id => current_student.id).length == 0 %>
        <td><%= link_to 'Bookmark', bookmark_path(book) %></td>
        <% else %>
        <td><%= link_to 'Unbookmark', bookmark_path(book) %></td>
        <% end %>

        <% if BorrowingHistory.is_book_active?(current_student.id, book.id)%>
        <td><%= button_to 'Return', return_path(book) %></td>
        <% else %>
        <% if BookLibraryMapping.fetch_book_quantity(book.id) != 0 and !book.special%>
        <td><%= button_to 'Checkout', checkout_path(book) %></td>
        <% else %>
        <% if BookHoldRequest.is_requested?(current_student.id, book.id)%>
        <td><%= button_to 'Cancel Request', request_path(book) %></td>
        <% else %>
        <td><%= button_to 'Request', request_path(book) %></td>
        <% end %>
        <% end %>
        <% end %>
        <% end %>
        
        <% if current_admin%>        
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div >
<% if current_admin%>
<%= button_to 'New Book', new_book_path %>
<% end%>
<% end %>
</div>